def setup_simulation_parameters(mode="cool_down"):
    """
    Sets up simulation parameters and initial conditions based on the specified mode.

    Args:
        mode (str): "cool_down" or "warm_up".

    Returns:
        dict: A dictionary containing all simulation parameters.
    """
    params = {}
    params['simulation_mode'] = mode

    # IT Equipment Properties
    params['P_IT_heat_source'] = 10000  # Heat generated by IT equipment (Watts)
    params['C_IT'] = 1.321e6      # Heat capacity of IT components (J/K) 1
    params['G_conv'] = 12000      # Convective heat conductance IT to Rack Air (W/K) 2

    # Data Centre and Air Properties (General)
    params['rho_air'] = 1.16 #3
    params['c_p_air'] = 1005.45 #4

    # Rack Air Properties
    params['V_freeSpace_per_rack_in_formula'] = 0.25
    params['n_racks'] = 5
    params['C_Rack'] = params['V_freeSpace_per_rack_in_formula'] * params['n_racks'] * \
                       params['rho_air'] * params['c_p_air']

    # Cooling System Properties
    params['m_dot_air'] = 2.26
    params['kappa'] = 0.7663
    params['COP_HVAC'] = 3.7

    # HVAC Control Parameters
    params['P_HVAC_max_watts'] = 10000.0
    params['P_HVAC_min_watts'] = 0.0

    # Cold Aisle Air Properties
    params['V_cAisle'] = 200
    params['C_cAisle'] = params['V_cAisle'] * params['rho_air'] * params['c_p_air']

    # Hot Aisle Air Properties
    params['V_hAisle'] = 10
    params['C_hAisle'] = params['V_hAisle'] * params['rho_air'] * params['c_p_air']

    # Cold Aisle Wall Properties
    params['alpha_cAisle'] = 16
    params['A_cAisle'] = 38
    params['R_cold_K_per_W'] = (0.7 / 1000)
    term1_Gcold_inv = 1 / (params['alpha_cAisle'] * params['A_cAisle']) \
        if (params['alpha_cAisle'] * params['A_cAisle']) > 0 else float('inf')
    params['G_cold'] = 1 / (term1_Gcold_inv + params['R_cold_K_per_W']) \
        if (term1_Gcold_inv + params['R_cold_K_per_W']) > 0 else params['alpha_cAisle'] * params['A_cAisle']
    params['C_cWall'] = 840e3
    params['T_out_Kelvin'] = 295.15
    params['T_out_Celsius'] = params['T_out_Kelvin'] - 273.15

    # TES Tank Properties
    """params['V_TES'] = 1000
    params['c_p_water'] = 4184
    params['rho_water'] = 1000
    params['T_TES_initial_Celsius'] = 25.0
    params['T_TES_initial_Kelvin'] = params['T_TES_initial_Celsius'] + 273.15
    params['C_TES'] = 1000 * params['rho_water'] * params['c_p_air']
    params['V_TES_discharge_max'] = 10
    params['V_TES_discharge_min'] = 0.0
    params['V_TES_charge_max'] = 10
    params['V_TES_charge_min'] = 0.0"""
    params['TES_kwh_cap'] = 20
    params['TES_kw_discharge_max'] = 5000 
    params['TES_kw_discharge_min'] = 0.0
    params['TES_discharge_efficiency'] = 0.9
    params['TES_kw_charge_max'] = 5000
    params['TES_kw_charge_min'] = 0.0
    params['TES_charge_efficiency'] = 0.9
    params['TES_initial_charge'] = 10
    

    # Simulation Parameters
    params['dt'] = 0.1
    params['simulation_time_minutes'] = 120 # Default simulation time
    params['begin_change'] = 20


 #T_IT: , T_Rack: , T_cAisle:  T_hAisle: 24.38, T_Air_in: 18.00
    if mode == "cool_down":
        params['T_Air_in_initial'] = 18.0
        params['T_cAisle_initial'] = 18.63
        params['T_cWall_initial_Celsius'] = params['T_out_Celsius'] + 2.0
        params['T_Rack_initial_Celsius'] = 24.38
        params['T_IT_initial_Celsius'] = 25.21
        params['T_hAisle_initial'] = 24.38

        params['T_target_Air_in_Celsius'] = 18  # Target HVAC supply air temperature (°C)
        params['T_cAisle_upper_limit_Celsius'] = None # Not used in cool_down mode
        # This flag indicates if HVAC is active during the warm-up phase (becomes True when limit is hit)
        params['warm_up'] = True # Not relevant for cool_down but define for consistency

    elif mode == "warm_up":
        params['T_Air_in_initial'] = 18.0
        params['T_cAisle_initial'] = 18.63
        params['T_cWall_initial_Celsius'] = params['T_out_Celsius'] + 2.0
        params['T_Rack_initial_Celsius'] = 24.38
        params['T_IT_initial_Celsius'] = 25.21
        params['T_hAisle_initial'] = 24.38
        params['T_target_Air_in_Celsius'] = 18.0  # Ultimate target HVAC supply air temperature (°C)
        params['T_cAisle_upper_limit_Celsius'] = 27.0 # Upper limit for T_cAisle to trigger HVAC
        # Start with a cooler data center
        # Start wall near initial air conditions or outside temp
        params['warm_up'] = "Before" # HVAC starts off, becomes True when T_cAisle hits limit
    else:
        raise ValueError("Invalid mode specified. Choose 'cool_down' or 'warm_up'.")

    return params
