"""Construct a conservative revision of first_edit.tex. No optimisation is executed."""
from pathlib import Path
import shutil,re,csv,json,difflib,html,hashlib
HERE=Path(__file__).resolve().parent
ROOT=HERE.parents[1]
SOURCE=ROOT/'paper/first_edit.tex'
OLD=ROOT/'paper/final_submission'
original=SOURCE.read_text(encoding='utf-8')
s=original
changes=[]
def replace(old,new,reason):
    global s
    if old not in s: raise ValueError('Missing replacement: '+old[:120])
    s=s.replace(old,new)
    changes.append({'reason':reason,'old':old,'new':new})
def span(start,end,new,reason):
    global s
    a=s.index(start); b=s.index(end,a)
    replace(s[a:b],new+'\n\n',reason)
def paragraph(start,new,reason):
    a=s.index(start); b=s.find('\n\n',a)
    replace(s[a:b],new,reason)
for folder in ('images','data','tables','supplement','review','build'):
    (HERE/folder).mkdir(exist_ok=True)
for p in (ROOT/'paper/images').glob('*'):
    if p.is_file():shutil.copy2(p,HERE/'images'/p.name)
for folder in ('data','tables'):
    shutil.copytree(OLD/folder,HERE/folder,dirs_exist_ok=True)
shutil.copy2(OLD/'references.bib',HERE/'references.bib')
bib=(HERE/'references.bib').read_text(encoding='utf-8')
bib=re.sub(r'(?m)(=\s*\{[^\n]*\})(\n\s*\w+\s*=)',r'\1,\2',bib)
(HERE/'references.bib').write_text(bib,encoding='utf-8')
shutil.copy2(SOURCE,HERE/'review/first_edit.tex')

# Document mechanics only: preserve the first edit's layout and earlier revision text.
replace(r'\newcommand{\rev}[1]{\textcolor{blue!70!black}{#1}}',r'\newcommand{\rev}[1]{#1}', 'Clean rendering; previous reviewer amendments remain in the text.')
replace(r'\usepackage{mathtools}',r'\usepackage{mathtools}'+'\n'+r'\usepackage{tabularx}', 'New annual results table uses tabularx.')
for oldkey,newkey in {'misaghian2022assessment':'Misaghian2023TIA','cao2022data':'Cao2022ApEn','fu2020assessments':'Fu2020ApEn','xu2023data':'Xu2023SPIE'}.items():
    replace('{'+oldkey+'}','{'+newkey+'}','Resolve inherited missing citation key to the existing matching bibliography entry.')
replace(r'\markboth{Journal of \LaTeX\ Class Files,~Vol.~XX, No.~XX, October~2025}',r'\markboth{Data Centre Flexibility}', 'Remove template journal placeholder.')
replace('Cost-optimised operation cuts daily electricity costs by 6.3\\%.','Cost-optimised operation cuts annual electricity costs by 5.05\\%.','Annual result replaces superseded daily result.')
replace('100 kW of upward flexibility sustained for 6.8 hours by a 1 MW data centre.','100 kW of upward flexibility sustained for six hours by a 1 MW IT-rated DC.','Current event result and rating convention.')
replace('Savings are most sensitive to price volatility and workload flexibility share.','Additional UPS capacity is assessed using annual savings and investment thresholds.','Current sensitivity scope and supervisor UPS emphasis.')
replace('computes the maximum feasible duration from this baseline','identifies a certified feasible duration from this baseline','Search supports feasible durations, not global maximality.')
replace('In contrast, downward flexibility (electricity load increase) relies on increasing power consumption of the cooling system, supported by the TES buffer, and charging the UPS, as advancing IT workload is constrained.','In contrast, downward flexibility (electricity load increase) combines changes in IT execution, cooling and storage; eligible work can execute earlier than in the baseline, but never before arrival.','Updated event mechanisms include advancing eligible work.')
replace('For the 1 MW case study, 100 kW of upward flexibility can be sustained for 6.8 hours at 00:15 but only 0.2 hours at 17:30, demonstrating the strong dependence of feasible duration on the baseline operating state, and a sensitivity analysis shows the accompanying 6.3\\% cost saving is most sensitive to electricity price volatility and the flexible workload share.','For the 1 MW IT-rated case study, 100 kW of upward flexibility can be sustained for six hours at noon and 1.25 hours at 06:00, demonstrating the strong dependence of feasible duration on the baseline operating state. Linked daily optimisation over 2025 gives a 5.05\\% annual electricity-cost saving; resource sensitivities examine workload share, UPS and TES capacity.','Replace all obsolete abstract results without shortening its background.')
replace("and the maximum duration for which this deviation can be sustained.","and the certified feasible duration for which this deviation can be sustained.",'Duration certification scope.')
replace('what is the maximum duration for which the data centre can sustain that deviation','for how long can the data centre sustain that deviation','Avoid unsupported maximum claim in research question.')
replace('(2) a cost-optimised baseline schedule against which grid-facing flexibility is measured, together with a component-level cost decomposition and a sensitivity analysis of the achievable savings; and (3) a duration-aware assessment that evaluates the feasible flexibility duration across a grid of start times and requested power deviations, including post-event recovery.', '(2) a duration-aware assessment that evaluates the feasible flexibility duration across a grid of start times and requested power deviations, including post-event recovery; and (3) a full-year evaluation of operational electricity-cost savings, with a component-level cost decomposition and resource sensitivities, including the incremental value of UPS capacity.','Contribution hierarchy: physical characterisation first, annual valuation supporting.')
replace('The remainder of this paper is structured as follows.', 'The annual evaluation uses linked daily optimisation to avoid basing the economic conclusions on a single price day. This rolling procedure supports the valuation of flexibility rather than constituting a new optimisation algorithm.\n\nThe remainder of this paper is structured as follows.','Explain annual role with an addition rather than rewrite introduction.')
replace('the maximum duration for which this flexibility can be provided.','a certified feasible duration for which this flexibility can be provided.','Align literature closing paragraph with retained search.')
replace('Importantly, the required computational work of every IT job is always executed in full within its delay tolerance, so flexibility is provided without sacrificing computational throughput or service quality.','The required computational work is preserved within the modelled execution windows. This maintains aggregate computational throughput under the adopted assumptions; application-specific service quality, task dependencies and server placement are not modelled.','Distinguish aggregate workload constraints from blanket SLA guarantee.')

# Existing nomenclature remains in the main document; update stale definitions/values.
replace('Set of time slots over a 24-hour planning horizon, representing potential arrival times for jobs. & $\\{1, \\dots, 96\\}$','Committed time slots of local day $d$; $T_d$ below. & 92, 96 or 100 slots','Annual calendar convention.')
replace('Extended planning horizon, allowing jobs arriving near the end of the horizon to be deferred within allowable bounds. & \\{1,...,96+$D^{\\text{max}}$\\}','Local-day core plus twelve look-ahead slots; $T_d^{\\mathrm{ext}}$ below. & $|T_d|+12$ slots','Look-ahead includes full site demand.')
replace(' & [1,...,96+$D^{\\text{max}}$] & -', ' & Absolute slot indices & -','Absolute indexing for carry-over.')
replace(' Redefined in Section \\ref{sec:scenario 3}.',' Original classes retained in Section \\ref{sec:scenario 3}.','Event cohorts retain original deadlines, not aggregate retranching.')
replace('Minimum allowable charging power of the UPS. & 40','Minimum allowable charging power of the UPS. & 0','No active minimum UPS power in retained runs.')
replace('Minimum allowable discharging power of the UPS. & 100','Minimum allowable discharging power of the UPS. & 0','No active minimum UPS power in retained runs.')
replace('Maximum allowable discharging power of the UPS. & 2700','Nominal UPS discharge rating; useful discharge also cannot exceed IT demand (at most 1000 kW). & 2700','Topology imposes effective discharge limit.')
replace('Energy stored in the UPS battery system at the end of time slot t.','Energy stored in the UPS battery system at the opening boundary of time slot t.','Consistent boundary-state indexing.')
replace('Maximum thermal charging rate of the TES tank.','Maximum thermal discharging rate of the TES tank.','Correct swapped nomenclature definition.')
# Previous replacement changes both matching phrases only once; repair the charging symbol row explicitly.
line=next(x for x in s.splitlines() if x.startswith('$Q^{\\mathrm{Chil}\\text{-}\\mathrm{TES}}_{\\mathrm{max}}$'))
replace(line,line.replace('discharging rate','charging rate'),'Correct TES charging-rate symbol.')
replace('$[14, 30]$','$[18, 30]$','Actual inlet temperature bounds.')
replace(r'\rev{$[18, 22.5]$ (Scen.~1--2); $[18, 23]$ (Scen.~3)}',r'$[18, 23]$ (all scenarios)','Same thermal limits in annual and event cases.')
replace('fixed at 7\\% of the average base-case IT-plus-cooling power.','calibrated at 7\\% of an earlier daily base-case IT-plus-cooling mean and then held fixed.','Auxiliary value is inherited calibration, not annually recalculated.')
replace('Maximum duration of flexibility provision. & [0–23:45]','Certified feasible duration of flexibility provision, capped by twelve hours and local-day end. & [0--12]','Current event grid.')
replace('Start time of flexibility provision. & [0–23:45]','Start time of flexibility provision, sampled hourly. & [00:00--23:00]','Current hourly event starts.')

# Keep both original workload tables and the contextual ranges; correct their interpretation and actual input summaries.
paragraph('Based on the review of the literature,',r'''Based on the review of the literature, a dataset of reported workload ratios and graphs over a 24-hour time horizon was compiled. Table~\ref{tab:workload-rates} retains the minimum, maximum and average values reported in that synthesis as context. The adopted workload ratios are modelling assumptions rather than measurements from a single facility. The ``Proposed'' columns now show hourly means of the quarter-hour inputs actually used in the annual calculations; they should not be reconstructed from the contextual range columns. \rev{The evidence base informing these assumptions is consolidated in Table~\ref{tab:workload-source-summary}. The retained range summaries do not establish a reproducible statistical derivation of each adopted input or a representative distribution across facilities. The exact 96 quarter-hour input rows are supplied in Supplementary Section~S1 and the accompanying data files.}''','Retain historical range information but distinguish it from actual solver inputs and unverified derivation.')
replace('Bounds and representative average CPU utilisation levels.','Context for CPU utilisation assumptions.','Avoid presenting cited ranges as enforced bounds.')
replace('Evidence Used to Construct the Workload Assumptions','Evidence Informing the Workload Assumptions','Distinguish motivation from reproducible data derivation.')
loads=list(csv.DictReader((HERE/'data/load_profiles.csv').open()))[:96]
shares=list(csv.DictReader((HERE/'data/shiftability_profile.csv').open()))[:96]
for h in range(24):
    pattern=rf'(?m)^{h:02d}--{h+1:02d} & .*?\\\\$'
    m=re.search(pattern,s);assert m
    cells=m.group().split(' & ')
    f=sum(float(r['flexible_load']) for r in loads[h*4:h*4+4])*25
    i=sum(float(r['inflexible_load']) for r in loads[h*4:h*4+4])*25
    cells[4]=f'{f:.2f}';cells[8]=f'{i:.2f}';cells[12]=f'{f+i:.2f} '+r'\\'
    replace(m.group(),' & '.join(cells),'Update proposed hourly workload means from retained quarter-hour inputs.')
replace('Stacked Proposed Workload Ratios Over 24 Hours','Adopted Quarter-Hour Workload Ratios Over 24 Hours','Figure will be plotted directly from active stored inputs.')
replace('Hourly Distribution of Shiftable Workload Under Different Deferral Windows (\\%)','Hourly Mean Tranche Shares in the Adopted Quarter-Hour Inputs (\\%)','Summary table is not the quarter-hour input itself.')
for k in range(1,5):
    m=re.search(r'(?m)^\\rev\{\$k='+str(k)+r'\$\}.*?\\\\$',s);assert m
    parts=m.group().split(' & ')
    vals=[sum(float(r[str(k)]) for r in shares[h*4:h*4+4])*25 for h in range(24)]
    replace(m.group(),' & '.join(parts[:2]+[f'{v:.2f}' for v in vals])+r' \\', 'Correct tranche summary using recorded quarter-hour fractions.')
paragraph(r'\rev{Table~\ref{tab:shiftable} presents',r'''\rev{Table~\ref{tab:shiftable} presents hourly mean shares of flexible workloads across the four delay tranches: tranche $k=1$ permits a final execution-interval start 30 minutes after arrival, $k=2$ 60 minutes, $k=3$ 2 hours, and $k=4$ 3 hours.} The percentages represent the relative distribution within the flexible workload. The solver uses the recorded quarter-hour fractions, rather than expanding these hourly means. Figure~\ref{fig:workload_ratios} shows the flexible and inflexible arrival utilisation. Together these profiles capture the time-dependent and duration-sensitive workload assumptions. A final eligible interval closes 15 minutes after its start: for example, a three-hour class arriving at noon may execute in the interval 15:00--15:15. Thus the class names denote deferral between interval starts, not continuous-time completion deadlines.''','Replace incorrect tranche example and disclose implemented deadline convention.')
replace('enabling the provision of upward or downward flexibility, respectively.','enabling the provision of downward or upward flexibility, respectively.','Correct reversed sign interpretation of increasing/decreasing utilisation.')

# IT formulation: retain equations and notation, revise extension and finite-horizon accounting.
replace('The formulation is defined over a 24 hour time horizon, which is discretized into 15-minute time slots. A 3 hour extension period is appended to this horizon, allowing the deferral of IT workloads from the final three hours of the original 24 hour window.', 'The formulation is discretized into 15-minute time slots. Each annual solve covers a local day $T_d$ and a 3 hour look-ahead, together denoted $T_d^{\\mathrm{ext}}$. For readability, $T$ and $T^{\\mathrm{ext}}$ below denote the current core and extended horizon. Work already unfinished at the opening boundary is included with its original arrival and deferral limit. New workload arrivals and full facility power are represented throughout the look-ahead.','Replace isolated daily model with full-site linked horizons.')
replace('of a job originating at slot $t \\in T$,','of a job originating at slot $t$, including carried arrivals and arrivals in the extended horizon,','Include carried and look-ahead cohorts.')
span('Under the load shifting scenario, the optimised power', 'IT jobs cannot be scheduled before their arrival',r'''Under the load shifting scenario, the optimised power and energy consumption are calculated using (\ref{eq:power_optimised}) and (\ref{eq:energy_optimised}). Full IT power is modelled in both the committed day and the look-ahead; baseline power is not subtracted from extension-period demand. This ensures that future work, cooling and storage interact through the same physical power balance. Annual settlement subsequently counts only committed intervals, as described in Section~\ref{sec:annual-operation}.

Let $\mathcal A_d$ denote the arrival/tranche pairs present in a horizon: unfinished cohorts carried from earlier days and new arrivals throughout $T_d^{\mathrm{ext}}$. Their currently available CPU-hours are $A_{t,k,d}$, equal to original work $R_t\alpha_{t,k}$ for a new cohort and to its residual work for a carried cohort. Let $W_{t,k}$ contain the eligible intervals within the current horizon and $L_d$ its final interval start. In (\ref{eq:power_optimised}), only eligible pairs contribute to execution at slot $s$. The same four-segment interpolation $\widehat f$ of Equation~\ref{eq:power_it} is used in both scenarios. Its implementation is specified in Section~\ref{sec:scenario 2}.''','Remove obsolete extension power subtraction and define exact finite-horizon workload accounting.')
replace('Constraint (\\ref{eq:job_completion}) guarantees that the total computational work performed for each tranche over its execution window matches the required demand for that tranche.','Constraint (\\ref{eq:job_completion}) requires completion when the final eligible interval lies within the horizon; otherwise it limits processing to the available work. Only execution in committed intervals reduces the work carried to the next day, so advisory look-ahead processing is never counted as completed work.','Finite-horizon completion versus residual carry.')
span('Finally, constraint (\\ref{eq:cpu_capacity_new})', '\\begin{figure*}[!t]\n\\label{fig:it-equations}',r'''Finally, constraint (\ref{eq:cpu_capacity_new}) enforces per-time-slot CPU capacity. At each slot $s$, the CPU utilisation equals the inflexible load plus the contributions of all eligible flexible tranches. The summed utilisation is bounded by $u_{\max}$, ensuring no schedule exceeds the available CPU capacity at the time of execution.''','Preserve explanation while aligning indices with eligible cohorts.')
a=s.index('& P^{\\mathrm{IT}}_{\\mathrm{opt}}(t) = \\begin{cases}')
b=s.index('\n\\end{flalign}',a)
replace(s[a:b],r'''& P^{\mathrm{IT}}_{\mathrm{opt}}(s)=\widehat f\!\left(u^{\mathrm{inflex}}(s)+\sum_{(t,k)\in\mathcal A_d:\,s\in W_{t,k}}u(t,k,s)\right),\quad s\in T^{\mathrm{ext}}. \label{eq:power_optimised} &''','Full-site piecewise-linear power applies throughout horizon.')
# Replace individual labelled equations, preserving their labels and all conceptual constraints.
def equation(label,text):
    global s
    lines=s.splitlines(); idx=next(i for i,l in enumerate(lines) if r'\label{'+label+'}' in l)
    start=idx
    while start>0 and (r'\nonumber' in lines[start-1] or r'\notag' in lines[start-1]):start-=1
    replace('\n'.join(lines[start:idx+1]),text,'Update implemented constraint '+label+'.')
equation('eq:util_bounds',r'& 0\leq u(t,k,s)\leq u_{\max},\quad (t,k)\in\mathcal A_d,\ s\in W_{t,k} \label{eq:util_bounds} \\')
equation('eq:power_base',r'& P^{\mathrm{IT}}_{\mathrm{base}}(s)=\widehat f\bigl(u^{\mathrm{inflex}}(s)+u^{\mathrm{flex,base}}(s)\bigr) \label{eq:power_base} \\')
equation('eq:feasibility',r'& u(t,k,s)=0\quad\text{if }s<t\text{ or }s>t+D_k,\quad (t,k)\in\mathcal A_d \label{eq:feasibility} \\')
equation('eq:alpha_sum',r'& \sum_{k\in K}\alpha_{t,k}=1\quad\text{for each new arrival }t \label{eq:alpha_sum} \\')
equation('eq:job_completion',r'''& \sum_{s\in W_{t,k}}u(t,k,s)\Delta t
\begin{cases}=A_{t,k,d},&t+D_k\leq L_d,\\ \leq A_{t,k,d},&t+D_k>L_d,\end{cases} \label{eq:job_completion} \\''')
equation('eq:cpu_capacity_new',r'& u^{\mathrm{inflex}}(s)+\sum_{(t,k)\in\mathcal A_d:\,s\in W_{t,k}}u(t,k,s)\leq u_{\max},\quad s\in T^{\mathrm{ext}}. \label{eq:cpu_capacity_new}')

# Existing storage and cooling equations stay in main, corrected to retained model.
replace('Furthermore, to ensure energy balance over the optimisation period, the energy level at the start and end of the cycle are constrained to be equal, as specified in (\\ref{eq:18}).','Furthermore, the opening energy of each day equals the preceding committed closing energy, as specified in (\\ref{eq:18}). Initial UPS energy is 600 kWh and the operational lower bound retains a 50\\% reserve. No daily cyclic recharge is imposed.','State carry replaces daily cycling.')
replace('whether it is charging from the grid, discharging to the grid, or powering the IT equipment to reduce the grid load.','whether it is charging from the grid or powering the IT equipment to reduce the grid load. Discharge cannot exceed IT demand, and the facility does not export electricity.','Correct implemented UPS topology.')
equation('eq:18',r'& E^{\mathrm{UPS}}_{d+1,\mathrm{start}}=E^{\mathrm{UPS}}_{d,\mathrm{core\ end}},\quad E^{\mathrm{UPS}}_{1,\mathrm{start}}=E^{\mathrm{UPS}}_{\mathrm{base}}. \label{eq:18} \\')
replace('for proportionally sized infrastructure, the reported power magnitudes scale approximately linearly with facility size.','transfer to a larger facility remains conditional on its workload, equipment ratios and operating limits.','Remove untested linear scalability claim while retaining scale discussion.')
replace('By allowing temperatures to fluctuate between $18$ and $22.5$ degrees, the masses act as a thermal buffer.','By allowing temperatures to fluctuate within their component-specific bounds (cold aisle $18$--$23$ degrees), the masses act as a thermal buffer.','Correct thermal bounds.')
replace('The thermal buffer allows the chiller\'s power consumption to be modulated without affecting IT operations.', 'The thermal buffer allows the chiller\'s power consumption to be modulated within the modelled IT operating limits. Gross cooling is additionally constrained to be at least IT heat generation; this adopted rule limits the amount of flexibility credited to thermal accumulation.','Disclose active conservative cooling rule.')
equation('eq:thermal_balance',r'& Q_{CA}(t)+Q_{HA}(t)+Q_R(t)+Q_{ITm}(t)=Q_{out}(t)+Q^{\mathrm{IT}}(t)-\kappa Q_{\mathrm{cool}}(t),\quad t\in T^{\mathrm{ext}} & \label{eq:thermal_balance} \\')
equation('eq:tes_energy_update',r'& E^{\mathrm{TES}}(t+1)=E^{\mathrm{TES}}(t)+[\eta^{\mathrm{TES}}_{\mathrm{ch}}Q^{\mathrm{Chil}\text{-}\mathrm{TES}}(t)-Q^{\mathrm{TES}\text{-}\mathrm{CRAC}}(t)/\eta^{\mathrm{TES}}_{\mathrm{dis}}]\Delta t,\quad t\in T^{\mathrm{ext}} & \label{eq:tes_energy_update} \\')
equation('eq:air_inlet_temp',r'& T_{Ain}(t)=T_{HA}(t+1)-Q_{\mathrm{cool}}(t)/(\dot m_a c_{pa}),\quad t\in T^{\mathrm{ext}} & \label{eq:air_inlet_temp} \\')
equation('eq:ite_temp',r'& T_{IT}(t+1)=T_{IT}(t)+\frac{3600\Delta t}{C_{IT}}[P^{\mathrm{IT}}(t)-G_{cv}(T_{IT}(t+1)-T_R(t+1))],\quad t\in T^{\mathrm{ext}} & \label{eq:ite_temp} \\')
equation('eq:rack_temp',r'& T_R(t+1)=T_R(t)+\frac{3600\Delta t}{C_R}[\dot m_a\kappa c_{pa}(T_{CA}(t+1)-T_R(t+1))+G_{cv}(T_{IT}(t+1)-T_R(t+1))],\quad t\in T^{\mathrm{ext}} & \label{eq:rack_temp} \\')
equation('eq:ca_temp',r'& T_{CA}(t+1)=T_{CA}(t)+\frac{3600\Delta t}{C_{CA}}[\dot m_a\kappa c_{pa}(T_{Ain}(t)-T_{CA}(t+1))-G_{cd}(T_{CA}(t+1)-T_{out})],\quad t\in T^{\mathrm{ext}} & \label{eq:ca_temp} \\')
equation('eq:ha_temp',r'& T_{HA}(t+1)=T_{HA}(t)+\frac{3600\Delta t}{C_{HA}}[\dot m_a\kappa c_{pa}(T_R(t+1)-T_{HA}(t+1))],\quad t\in T^{\mathrm{ext}} & \label{eq:ha_temp} \\')
equation('eq:cooling_power_constraint',r'& P^{\mathrm{IT}}(t)\leq Q_{\mathrm{cool}}(t)\leq(T_{HA}(t+1)-T_{CA,min})\dot m_a c_{pa},\quad t\in T^{\mathrm{ext}} & \label{eq:cooling_power_constraint} \\')
equation('eq:tes_energy_cycle',r'& E^{\mathrm{TES}}_{d+1,\mathrm{start}}=E^{\mathrm{TES}}_{d,\mathrm{core\ end}},\quad E^{\mathrm{TES}}_{1,\mathrm{start}}=0.5E^{\mathrm{TES}}_{\max} & \label{eq:tes_energy_cycle} \\')
replace(r'& E^{\mathrm{TES}}(t) \le E^{\mathrm{TES}}_{\mathrm{max}}',r'& 0\le E^{\mathrm{TES}}(t) \le E^{\mathrm{TES}}_{\mathrm{max}}','Explicit TES lower energy bound.')
replace('employing an explicit forward Euler method.','employing an implicit backward Euler method. Here $t+1$ denotes the boundary after interval $t$ (the same boundary as $t+\\Delta t$ in the UPS equation). In Equation~\\eqref{eq:thermal_balance}, $Q_j(t)=C_j[T_j(t+1)-T_j(t)]/(3600\\Delta t)$ and the effective cooling of the represented nodes is $\\kappa Q_{\\mathrm{cool}}$, consistent with the calibrated airflow factor in the state equations.','Match actual implicit discretisation and aggregate heat balance.')
replace(r'$Q_{\mathrm{out}}(t) = G_{cd} (T_{\mathrm{out}} - T_{CA}(t))$',r'$Q_{\mathrm{out}}(t) = G_{cd} (T_{\mathrm{out}} - T_{CA}(t+1))$','Implicit external heat-flow convention.')
replace('enforces a cyclic energy balance, ensuring the final state of charge equals the initial state.','passes the committed closing state to the next day, without requiring a daily return to the initial state.','Remove obsolete TES cycle explanation.')
replace('constraint \\eqref{eq:temp_constraints} enforces the upper and lower temperature bounds for all thermal components.','constraint \\eqref{eq:temp_constraints} enforces the upper and lower temperature bounds for all thermal components, including the final state boundary. Initial IT, rack, cold-aisle and hot-aisle temperatures are $(28.5,26,20,27)^\\circ$C; subsequent daily openings inherit all four states. Storage energy bounds also apply at the final boundary.','Clarify all state boundaries and initial temperatures.')

# Scenario descriptions retain original structure and objective notation.
replace('(i) to what extent can an integrated optimum energy management algorithm reduce operating cost, and \\rev{(ii) using this cost-optimised operation as a baseline, how long can a requested upward or downward power deviation be sustained, for any given start time, without violating service levels?}', '(i) using cost-optimised operation as a baseline, how long can a requested upward or downward power deviation be sustained, for any given start time, while meeting the modelled workload and operating constraints; and (ii) to what extent can an integrated optimum energy management algorithm reduce annual electricity cost?','Order research questions by supervisor priority.')
replace('their optimal 24 hour schedule and then uses any remaining capacity to participate in flexibility services to generate additional revenue.','their daily operating schedule and then assesses the remaining capacity for flexibility services. The annual analysis measures electricity-cost savings; additional service revenue is not calculated.','Annual operating context and limited economic scope.')
replace('no optimisation; all workload inflexible, storage idle, constant $T_{CA}$', 'workload at arrival; storage idle; cooling optimised','Correct workflow benchmark.')
replace('single MILP over 24 h + 3 h extension','linked daily MILPs over 2025; full-site 3 h look-ahead','Update existing workflow rather than replace diagram.')
replace('Scenario 1 provides the unoptimised cost benchmark','Scenario 1 provides the workload-at-arrival cost benchmark','Correct workflow caption.')
replace('quantifies the maximum feasible flexibility duration','identifies certified feasible flexibility durations','Correct workflow search claim.')
paragraph('A hypothetical data centre with 1 MW IT capacity',r'''A hypothetical data centre with 1 MW IT capacity and associated infrastructure is considered. Annual electricity prices are the 2025 Great Britain day-ahead Intermittent Market Reference Prices (IMRP) published by the Low Carbon Contracts Company~\cite{lccc_imrp_actuals}. Each hourly price is applied to four quarter-hour intervals, retaining negative values. Table~\ref{tb:energy_price} gives prices for the selected illustrative day, 22 September 2025; annual costs use all 365 days. The final look-ahead uses actual 1 January 2026 prices rather than repeating an earlier day's prices. All principal parameter values remain detailed in Table~\ref{tb:nomenclature}. The 1 MW value is the IT rating, while the structural grid-import bound is 1,723.095 kW including cooling, UPS charging and auxiliaries. Workload profiles repeat by local clock time, with fixed ambient temperature and COP.''','Replace synthetic daily prices with actual annual series and representative day.')
prices=list(csv.DictReader((HERE/'data/price_timeline.csv').open()))
# Price column/timestamp names are resolved from the retained file, not inferred silently.
(HERE/'review/price_columns.json').write_text(json.dumps(list(prices[0]),indent=2))
# Representative-day price row is prepared by the asset helper after column inspection.
day_prices=[r for r in prices if r['local_date']=='2025-09-22']
assert len(day_prices)==96
old_price_line=next(l for l in s.splitlines() if l.startswith(r'\textbf{Price (GBP/MWh)}'))
replace(old_price_line,r'\textbf{Price (GBP/MWh)} & '+' & '.join(f"{float(day_prices[h*4]['settlement_price_gbp_per_mwh']):.2f}" for h in range(24))+r' \\', 'Replace synthetic prices with actual selected-day reference prices.')
replace('Day-Ahead Energy Prices','Day-Ahead Reference Prices on 22 September 2025','Label updated daily illustration.')
replace('This scenario calculates the overall cost without any optimisation or flexibility utilisation.','This scenario calculates the overall cost with workload executed at arrival and without UPS or TES dispatch, while cooling is cost optimised within the same thermal limits as Scenario 2.','Match reformed baseline.')
replace('The UPS and TES tank are not utilised, since there is no optimisation in place to schedule their use, and so will not incur any cost in this scenario.','The UPS and TES tank are not utilised and so incur no dispatch electricity cost in this scenario.','Cooling optimisation does exist.')
replace('it is set to a fraction $\\gamma_{\\mathrm{OD}}=0.07$ (7\\%) of the average base-case IT-plus-cooling power over the 24-hour horizon, giving the constant value reported in Table~\\ref{tb:nomenclature}, and it is held constant in all scenarios.','it was calibrated as a fraction $\\gamma_{\\mathrm{OD}}=0.07$ (7\\%) of an earlier daily base-case IT-plus-cooling mean of 758.5 kW, giving the constant value reported in Table~\\ref{tb:nomenclature}, and it is held constant in all scenarios rather than recalculated from annual operation.','Preserve auxiliary calibration equation with correct scope.')
replace('Additionally, all IT workload is considered inflexible and the temperature of the DC is constrained to a constant $22.5$ degrees. These adaptations result in a base case where the DC operates without utilising any flexibility.','Additionally, all IT workload executes at arrival, while temperatures evolve within the same bounds as in the coordinated case. These adaptations isolate the additional benefit of workload shifting and storage coordination beyond cost-optimised cooling.','Remove constant-temperature and wholly-inflexible baseline claims.')
replace(r'\frac{1}{|T|}\sum_{t\in T}\left(P^{\mathrm{Grid}}_{\mathrm{IT}}(t) + P^{\mathrm{Chil}\text{-}\mathrm{CRAC}}(t)\right)',r'\overline P^{\mathrm{legacy}}_{\mathrm{IT+cool}}=0.07\times758.5=53.095\ \mathrm{kW}','Auxiliary equation describes fixed historical calibration.')
replace('the sensitivity of the achieved savings to the volatility of these prices is evaluated in Section~\\ref{sec:sensitivity}','the annual price variation is represented directly, while resource sensitivities are evaluated in Section~\\ref{sec:sensitivity}','Remove superseded price-spread experiment.')
replace(r'\cdot \Delta t \cdot \pi(t)',r'\cdot \Delta t \cdot \pi(t)/1000','Consistent kW to MW conversion for GBP/MWh prices.')
replace('where $\\pi(t)$ is the day-ahead spot energy price at time $(t)$.','where $\\pi(t)$ is the signed day-ahead reference price at time $(t)$ in GBP/MWh; the factor $1/1000$ converts kW to MW. The expression is settled over each committed day and summed over 2025.','Signed-price and annual accounting units.')
paragraph(r'\rev{The resulting optimisation problem is a Mixed-Integer Linear Program',r'''\rev{The resulting optimisation problem is a Mixed-Integer Linear Program (MILP), as it includes binary variables for the UPS charging/discharging status and TES operation alongside continuous power, energy, temperature and CPU-utilisation decision variables.} In this scenario, the integrated DC model is used in linked daily MILP optimisations over the full year. To maintain the model's linearity, the non-linear function in Equation~\ref{eq:power_it} is linearized using a piecewise linear approximation. This technique approximates the non-linear curve with a series of connected line segments. The implemented four segments have breakpoints $b_i=(i/4)^{1.5}$, $i=0,\ldots,4$, and use Pyomo's DLOG representation; the maximum approximation error is 6.241 kW (0.624\% of rated IT power). Scenario 1 evaluates the identical interpolation at its fixed utilisation. The model was implemented in Python using the Pyomo modelling library and solved using HiGHS. The retained run record identifies Python 3.12.0, Pyomo 6.10.1 and HiGHS 1.15.1 on Windows 11 with an AMD Ryzen 7 9800X3D. The standard daily time limit is 300 s and requested relative MILP gap 0.1\%; feasible time-limited solutions and diagnostic checks are disclosed in Supplementary Section~S5. These linked solves are not a single globally optimal year-long programme.''','Replace obsolete SOS2/SCIP, runtime and universal optimality statements.')
replace(r'\subsection{Scenario 3: Flexibility Duration Calculation}',r'\input{annual_operation.tex}'+'\n\n'+r'\subsection{Scenario 3: Flexibility Duration Calculation}','Add concise annual procedure in existing Scenario 2.')
replace('the maximum duration for which the DC can sustain specified levels of flexibility magnitude is determined.','a certified feasible duration for which the DC can sustain specified levels of flexibility magnitude is determined.','Event search scope.')
replace('the longest continuous period $\\tau$ is determined','a continuous period $\\tau$ is identified','Avoid global maximum claim.')
paragraph('The flexibility analysis takes the optimised baseline',r'''The flexibility analysis takes the optimised baseline from Scenario \ref{sec:scenario 2} as the reference trajectory and fixes the initial states at the chosen start time $t_0$. Each IT job may already have been shifted by a variable amount, so its remaining flexibility is its original execution window less the time already elapsed. The original four classes are retained, but unfinished work is tracked for each arrival/tranche pair rather than aggregated into new delay classes. Equations~\ref{eq:k_def} and \ref{eq:Dk_def} express the remaining eligible execution window. This prevents a job that has already been deferred from receiving a fresh full deferral allowance.''','Replace obsolete 12-tranche approximation with exact carried cohort ledger.')
replace('The only other constraint change to the formulation described in Section~\\ref{sec: methodology}, is the core requirement','Another constraint added to the formulation described in Section~\\ref{sec: methodology} is the core requirement','Recovery adds further constraints as well.')
a=s.index('\\begin{flalign}',s.index('Another constraint added'));b=s.index('\\end{flalign}',a)+len('\\end{flalign}')
replace(s[a:b],r'''\begin{align}
& K=\{1,2,3,4\},\quad (t,k)\in\mathcal A_{t_0} \label{eq:k_def} \\
& W^{\mathrm{event}}_{t,k}=\{s:\max(t,t_0)\leq s\leq t+D_k\}\cap T^{\mathrm{event}} \label{eq:Dk_def} \\
& \left|P^{\mathrm{Grid}}(t)-P^{\mathrm{Grid}}_{\mathrm{base}}(t)-\Delta P\right|\leq P_{\mathrm{tol}},\quad t_0\leq t<t_0+\tau. \label{eq:flex_constraint}
\end{align}''','Symmetric target tracking and exact remaining execution windows.')
span('For each start time $t_0$ and flexibility magnitude $\\Delta P$, the feasibility',r'\subsection{\rev{Sensitivity Analysis Design}}',r'''For each start time $t_0$ and flexibility magnitude $\Delta P$, the feasibility of providing the given $\Delta P$ is tested over a series of durations. \rev{The optimisation described in Scenario 2 is run for each duration over the event and a further twelve-slot (three-hour) recovery window. The flexibility constraint in Equation~\ref{eq:flex_constraint} applies only during service delivery. During recovery, all physical, thermal, storage and workload constraints continue to apply but the grid-power deviation is no longer enforced.} At recovery boundary $H=t_0+\tau+3$ h, UPS and TES energy must be at least their undisturbed Scenario 2 values, each of the four temperatures must be within $0.05^\circ$C of its corresponding value, and every cohort's unfinished work must be no greater than its undisturbed residual plus $10^{-7}$ CPU-hours. Recovery work remains schedulable within its original execution windows; it is not all reclassified as inflexible. These comparative conditions prevent additional depletion or unfinished work from being left beyond recovery.

If an audited feasible solution is found for a given duration $\tau$, the DC can provide that level of flexibility for the given duration. The same feasibility test is then repeated for a longer duration; shorter candidates are explored after unsuccessful trials. The duration is modified using a logarithmic search, with an adjacent-duration check. Candidate durations are multiples of 15 minutes and capped at twelve hours or the remaining local day. An unresolved solve is not proof of infeasibility. Moreover, changing $\tau$ changes the recovery boundary and its reference states, so adjacent checks do not prove that all longer durations are infeasible. The results are therefore certified feasible durations found by the search, with cap-reaching and unresolved-next-step cases identified separately. Supplementary Section~S3 gives the full procedure and status conventions.

The assessment uses 22 September 2025, selected by the smallest standardised distance to twelve annual daily price, demand, cost, utilisation and opening-state features among eligible 96-slot days. Starts are sampled hourly; requests are $-100$ to $-500$ kW in 50 kW steps and $+25$, $+50$ and $+75$ kW, giving 288 combinations. Each event inherits the actual coordinated state and cohort ledger, without preconditioning. All scenarios retain the same $18$--$23^\circ$C cold-aisle bounds. The selected day illustrates state-dependent capability; it does not measure annual service availability.''','Update event algorithm, recovery, sampling, caps and common thermal limits.')
paragraph(r'\rev{To assess the robustness of the cost-optimisation results',r'''\rev{To assess the dependence of the cost-optimisation results on resource assumptions, a one-at-a-time (OAT) sensitivity analysis is performed around the base case, covering the IT load flexibility ratio and equipment sizing. The flexible workload share is scaled by moving load between the flexible and inflexible pools while preserving the total CPU demand in every time slot, so that the flexibility share is isolated from the demand level; at high multipliers the share saturates in slots that are already almost fully flexible. The TES and UPS energy capacities are scaled while keeping their charge/discharge power limits unchanged, isolating the sizing of the energy buffers. Multipliers are $0.5$, $0.75$, $1.25$ and $1.5$, with the shared central case completing each curve. All cases cover 365 days and use the same workload-at-arrival annual comparator. Storage initial energy fractions and the 50\% UPS reserve fraction are preserved as capacities change. Annual observed prices replace the earlier separate price-volatility perturbation. The results are presented in Section~\ref{sec:sensitivity}.} Additional UPS savings are compared with annualised incremental investment, using a capital recovery factor; the main results give a compact screen and Supplementary Section~S6 states its assumptions.''','Use only completed annual resource sensitivities and add UPS screen.')

# Result editing is isolated in a separate function to retain as much explanatory wording as possible.
exec((HERE/'revise_results.py').read_text(encoding='utf-8'))
(HERE/'main.tex').write_text(s,encoding='utf-8')
(HERE/'review/change_operations.json').write_text(json.dumps(changes,indent=2,ensure_ascii=False),encoding='utf-8')
(HERE/'review/first_edit_to_minimal.patch').write_text(''.join(difflib.unified_diff(original.splitlines(True),s.splitlines(True),fromfile='first_edit.tex',tofile='minimal_revision/main.tex')),encoding='utf-8')
print(f'Wrote minimal revision: {len(changes)} documented replacement operations; original unchanged.')
